### ISSUE TITLE
preprocess and create numpy arrays

### ISSUE THREAD

**Issue by 1632325673** [SaharAlmahfouzNasser/MRI-SuperResolution#2]
I'm sorry to bother you，Which part of the dataset is preprocessed to create a numpy array.

**Comment by SaharAlmahfouzNasser** [comment]
Hi,
As you might know SuperMUDI dataset contains (.nii.gz) files for both the low-resolution as well as the high-resolution volumes.
In the dataloader.py we convert each (.nii.gz) file into a NumPy array using a package called nibabel. 
https://github.com/SaharAlmahfouzNasser/MRI-SuperResolution/blob/4cfd66fe6eefa3ab9dec106bdddc728617472a03/dataloader.py#L12
 After getting the 4D numby array, we select a 3D array from it for every call of the function (__getitem__).
 https://github.com/SaharAlmahfouzNasser/MRI-SuperResolution/blob/4cfd66fe6eefa3ab9dec106bdddc728617472a03/dataloader.py#L19
 Does this answer your question?

**Comment by 1632325673** [comment]
OK, thank you for your answer




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月12日(星期六) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SaharAlmahfouzNasser/MRI-SuperResolution] preprocess and create numpy arrays (Issue #2)






嗨
你可能知道 Super MUDI数据集包含低分辨率卷和高分辨率卷的(. nii . gz )文件。
在 data loader . py 中，我们使用一个称为 ni babel 的包将每个（. nii . gz ）文件转换成 Num Py 数组。
https://github.com/SaharAlmahfouzNasser/MRI-SuperResolution/blob/4cfd66fe6eefa3ab9dec106bdddc728617472a03/dataloader.py#L12
在得到 4D numby 数组后，我们从其中选择一个 3D 数组用于函数的每次调用（盖提坦).
https://github.com/SaharAlmahfouzNasser/MRI-SuperResolution/blob/4cfd66fe6eefa3ab9dec106bdddc728617472a03/dataloader.py#L19
这样回答你的问题了吗？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
随时随地使用 GitHub Mobile 进行分流通知,以便监察办或机器人. 
***@***.***与&gt;
